mylife/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('journey.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journey/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
import magic


#not secure
ext_validator = FileExtensionValidator(['jpeg','pdf','png']) 

#creating variables for image validation using python magic
def validate_image(file):
    accept = ['image/jpeg','application/pdf','image/png']
    image_type = magic.from_buffer(file.read(1024), mime=True)
    if image_type not in accept:
        raise ValidationError('unsupported type')


class Document(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title 

class DocumentImage(models.Model):
    document = models.ForeignKey(Document, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='documents/',validators=[ext_validator,validate_image])

    def __str__(self):
        return f"Image for {self.document.title}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True,blank=True, upload_to='profile_pics')
    profile_bio = models.CharField(null=True,blank=True,max_length=500)
    first_name = models.CharField(null=True,blank=True,max_length=100)
    last_name = models.CharField(null=True,blank=True,max_length=100)
    house_address = models.CharField(null=True,blank=True,max_length=100)
    phone_number = models.CharField(null=True,blank=True,max_length=100)
    city = models.CharField(null=True,blank=True,max_length=100)
    state = models.CharField(null=True,blank=True,max_length=100)
    country = models.CharField(null=True,blank=True,max_length=100)
    gender = models.CharField(max_length=10, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'Other')], default='O')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


class EmergencyContact(models.Model):
    RELATIONSHIP_CHOICES = [
        ('brother', 'Brother'),
        ('sister', 'Sister'),
        ('mother', 'Mother'),
        ('father', 'Father'),
        ('friend', 'Friend'),
        ('co_worker', 'Co-Worker'),
        ('business_partner', 'Business Partner'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    relationship = models.CharField(max_length=20, choices=RELATIONSHIP_CHOICES)
    email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return f'{self.name} - {self.relationship}'
    

#user automatically getting profile
def create_profile(sender,instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
post_save.connect(create_profile,sender=User)


class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Feedback from {self.user.username} - {self.created_at.strftime('%Y-%m-%d')}"

templates/activation_message.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>Please check your email to activate your account</h1>
{% endblock %}

templates/base.html
<!-- myapp/templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">YOLO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Life
              </a>
              {% if user.is_authenticated %}
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'documents' %}">My Document</a>
                <a class="dropdown-item" href="{% url 'document_create' %}">Create Document</a>
                <a class="dropdown-item" href="{% url 'profile' user.pk %}">My Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'settings' %}">Settings</a>
             
              </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About us</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact us</a>
            </li>
           </ul>
            <a class="nav-link" href="{% url 'logout' %}">Log out</a>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">Log in</a>
            <a class="nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
        </div>
      </nav> -->
      
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home'%}">MyLife</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'profile' user.pk %}">My Profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'documents' %}">Documents</a></li>
            <form method="post" action="{% url 'deactivate_account' %}">
              {% csrf_token %}
              <!-- <button type="submit">Yes, Deactivate my Account</button> -->
              <li class="nav-item"><a class="nav-link" href="{% url 'deactivate_account' %}">Logout</a></li>
          </form>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>




    <div class="container">
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      {% endif %}
        {% block content %}
        
        {% endblock %}
    </div>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap JS (and Popper.js for dropdown functionality) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/deactivate_account.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}About{% endblock %}
<h2>Are you sure you want to deactivate your account?</h2>
<form method="post" action="{% url 'deactivate_account' %}">
    {% csrf_token %}
    <button type="submit">Yes, Deactivate my Account</button>
</form>
<a href="{% url 'profile' %}">Cancel</a>
{% block content %}

{% endblock %}

templates/document_edit.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}

<div class="container mt-5">
   
    <form method="POST" enctype="multipart/form-data">
        <h1>Edit Document</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
        <a href="{% url 'document_view' form.instance.pk %}" class="btn btn-secondary mt-3">Cancel</a>
    </form>
   
    
</div>

{% endblock %}

templates/document_view.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
<!-- <div class="container mt-5">
    <h1>{{ document.title }}</h1>
    <p>Created at: {{ document.created_at|date:"F j, Y, g:i a" }}</p>
    <p>Last updated: {{ document.updated_at|date:"F j, Y, g:i a" }}</p>
    <hr>
    <div class="content">
        <p>{{ document.content }}</p>
    </div>
    {% for image in document.images.all %}
        <div class="mt-4">
            <img src="{{ image.image.url }}" class="img-fluid" alt="Document Image" width="100px" height="100px">
        </div>
    {% endfor %}
    <hr>
    <a href="{% url 'document_edit' document.pk %}" class="btn btn-primary">Edit Document</a>
    <a href="{% url 'documents' %}" class="btn btn-secondary">Back to Documents</a>
</div> -->

    <div class="container my-5">
    <div class="card shadow">
      <div class="card-body">
        <!-- Document Title -->
        <h2 class="card-title mb-3">Document Title: <strong>{{ document.title }}</strong></h2>

        <!-- Document Description -->
        <p class="card-text">
          <strong>Description:</strong> {{ document.content }}
        </p>

        <!-- Date -->
        <p class="card-text">
          <strong>Date Created:</strong> {{ document.created_at|date:"F j, Y, g:i a" }}
          <strong>Last updated:</strong> {{ document.updated_at|date:"F j, Y, g:i a" }}
        </p>

        <!-- Attached Image -->
        {% for image in document.images.all %}
        <div class="my-4">
          <h5>Attached Image:</h5>
          <img src="{{ image.image.url }}" class="img-fluid" alt="Document Image" width="100px" height="100px">
        </div>
        {% endfor %}

        <!-- Back Button -->
        <a href="{% url 'documents' %}" class="btn btn-secondary">Back to Documents</a>
        <a href="{% url 'document_edit' document.pk %}" class="btn btn-sm btn-warning">Edit</a>
        <button class="btn btn-sm btn-danger">
          <a href="{% url 'document_delete' document.id %}">Delete</a>
        </button>
      </div>
    </div>
    </div>
{% endblock %}

templates/emergency_contact.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}

    <div class="container mt-5">
        <h2>{{ form.instance.pk|yesno:"Edit,Add" }} Emergency Contact</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">{{ form.instance.pk|yesno:"Update,Add" }} Contact</button>
            <button type="submit" class="btn btn-warning"><a href="{% url 'emergency-contact-list' %}" >Back to Contacts</a></button>
            <button type="submit" class="btn btn-danger"><a href="{% url 'emergency-contact-add' %}" >Add Emergency Contact</a></button>
        </form>
        
    </div>
    <div class="container mt-5">
        <h2>Your Emergency Contacts</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Relationship</th>
                    <th scope="col">Email</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in contacts %}
                <tr>
                    <td>{{ contact.name }}</td>
                    <td>{{ contact.phone }}</td>
                    <td>{{ contact.get_relationship_display }}</td> <br>
                    <td>{{ contact.email }}</td>
                    <td>
                        <a href="{% url 'emergency-contact-edit' contact.id %}" class="btn btn-warning btn-sm">Edit</a>
                        <form action="{% url 'emergency-contact-delete' contact.id %}" method="POST" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/home.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <div class="text">
        <h1>WELCOME TO MY-LIFE</h1>
        <p>Join us and start saving up your life achievement for your loved ones,<br>because everyday we wake up and go out there to make our daily bread...only God can gurantee our safety back home. <br>Use this moment now and start making life easy for the next generation you bringing into the world and for the love once you will leave while you are gone.</p>
    </div>
    <div class="image">
        <img src="https://images.unsplash.com/photo-1483546363825-7ebf25fb7513?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Sample Image">
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    
    <form method="post">
        <h2>Login</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
        
            <a href="{% url 'password_reset'%}" class="btn btn-danger">Reset your password</a>
       
    </form>
    
</div>
</body>
</html>
{% endblock %}

templates/password_change.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block content %}

    <form method="post">
        <h2>Change Your Password</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Change Password</button>
        <a href="{% url 'profile' request.user.id %}" class="btn btn-success">Back to Profile</a>
    </form>
    
{% endblock %}

templates/password_reset.html
{% extends "base.html" %}

{% block content %}
<div>
  <h2>Password Reset</h2>
  <p>Enter your email address below and we'll send you a link to reset your password.</p>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send Password Reset Email</button>
  </form>

  <p><a href="{% url 'login' %}">Back to Login</a></p>
</div>
{% endblock %}

templates/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
  <h2>Set New Password</h2>
  <p>Please enter your new password twice below:</p>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
{% endblock %}

templates/password_reset_done.html
{% extends "base.html" %}

{% block content %}
  <h2>Password Reset Sent</h2>
  <p>If the email address you entered is associated with an account, you'll receive an email with instructions on how to reset your password.</p>
  <p>Please check your email inbox.</p>

  <p><a href="{% url 'login' %}">Back to Login</a></p>
{% endblock %}

templates/profile_details.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
{% if profile_details %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header text-center bg-dark text-white">
            <h2>{{profile_details.user.username}}'s profile</h2>
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-md-6">
                    <h5>First Name:</h5>
                    <p>{{ user.profile.first_name }}</p>
                </div>
                <div class="col-md-6">
                    <h5>Last Name:</h5>
                    <p>{{ user.profile.last_name }}</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-6">
                    <h5>Gender:</h5>
                    <p>{{ user.profile.gender }}</p>
                </div>
                <div class="col-md-6">
                    <h5>Phone Number:</h5>
                    <p>{{ user.profile.phone_number }}</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-6">
                    <h5>Home Address:</h5>
                    <p>{{ user.profile.house_address }}</p>
                </div>
                <div class="col-md-6">
                    <h5>City:</h5>
                    <p>{{ user.profile.city }}</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-6">
                    <h5>State:</h5>
                    <p>{{ user.profile.state }}</p>
                </div>
                <div class="col-md-6">
                    <h5>Country:</h5>
                    <p>{{ user.profile.country }}</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-12">
                    <h5>Bio:</h5>
                    <p>{{ user.profile.profile_bio }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
<a href="{% url 'profile_info' %}" class="btn btn-primary" >Edit Your Details</a>
<a href="{% url 'profile' pk %}" class="btn btn-primary" >Back to profile</a>
</div>
{% endif %}
{% endblock %}

templates/write_feedback.html
<!-- myapp/templates/home.html -->
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block content %}
  <!-- Feedback Section -->
  <div class="container my-5">
    

    <!-- Feedback Form -->
    <form method="POST" class="needs-validation" novalidate>
        <h1 class="mb-4 text-center">Write to Us</h1>
      {% csrf_token %}
      <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ request.user.username }}" readonly required>
      </div>
      <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" value="{{ request.user.email }}" readonly required>
      </div>
      <div class="mb-3">
        <label for="content" class="form-label">Your Message</label>
        <textarea class="form-control" id="content" name="content" rows="5" placeholder="Write your feedback here..." required></textarea>
      </div>
      <div class="d-grid">
        <button type="submit" class="btn btn-primary">Submit Feedback</button>
      </div>
    </form>
    <a href="{% url 'feedback_history' %}">Check feedback History</a>
  </div>

{% endblock %}